### ISSUE TITLE
Is this theme based on Creative by Bootstrapious?

### ISSUE THREAD

**Issue by ondrique** [datocms/gatsby-portfolio#16]
Hey guys,

This theme looks really similar to my [Creative theme](https://bootstrapious.com/p/creative-portfolio). Did you use it as a base? If so, let me know, thanks!

Cheers,

Ondrej, Bootstrapious

**Comment by stefanoverna** [comment]
Hi! Yes we definitely use your template as a base for our demos!

**Comment by ondrique** [comment]
Hey Stefano,

Thanks for getting back to me. 

Sorry to say so, but you would need to add a backlink attribution to the template's footer to respect my [license conditions](https://bootstrapious.com/p/creative-portfolio#licenseConditions) - _(Template by [Bootstrapious.com](https://bootstrapious.com/p/creative-portfolio))_. If you would prefer not to, please purchase an Extended Attribution-Free License (one would be enough for your CMS demos).

Thanks for understanding, have a great day!

**Comment by stefanoverna** [comment]
Absolutely, no problem. We should have done that long ago! Give us a couple of weeks ok? :)

—
Stefano Verna

DatoCMS

--- original message ---
On July 15, 2020, 12:08 PM GMT+2 notifications@github.com wrote:



Hey Stefano,

Thanks for getting back to me.

Sorry to say so, but you would need to add a backlink attribution to the template's footer to respect my license conditions - (Template by Bootstrapious.com). If you would prefer not to, please purchase an Extended Attribution-Free License (one would be enough for your CMS demos).

Thanks for understanding, have a great day!

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by ondrique** [comment]
Perfect, thanks a lot! ✌
